"""The database boundary.

SQLite is the development and test adapter; Oracle is the production store.
This protocol is what holds the two to the same behaviour, and it is what the
contract suite certifies a new adapter against.

It is not a generality device. Orchestration is ISRP's, with one consumer, and
makes no claim to being reusable elsewhere. This boundary exists because ISRP
runs on two databases, which is a different problem.
"""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from .states import Owner


class WorkflowRepository(Protocol):
    """Persistence boundary implemented by database-specific adapters.

    An `owner` is the pair (owner_type, owner_id) naming the aggregate a row
    belongs to: an ISRP request or an ISRP assessment. Adapters accept a plain
    tuple as readily as an Owner.
    """

    def transaction(self) -> AbstractContextManager[None]: ...
    def import_template(self, template: dict[str, Any]) -> dict[str, int]: ...
    def list_templates(self) -> list[dict[str, Any]]: ...
    def get_template(self, version_id: int) -> dict[str, Any] | None: ...
    def get_published_version(self, version_id: int) -> dict[str, Any] | None: ...
    def fsm_initial_state(self, fsm_version_id: int) -> str: ...
    def find_fsm_transition(self, fsm_version_id: int, state: str, action: str) -> dict[str, Any] | None: ...
    def state_is_terminal(self, fsm_version_id: int, state: str) -> bool: ...
    def state_meta(self, fsm_version_id: int, state: str) -> dict[str, Any]: ...
    def fsm_has_state(self, fsm_version_id: int, state: str) -> bool: ...

    # --- the two orchestrated aggregates ------------------------------------
    def create_aggregate(self, owner_type: str, data: dict[str, Any],
                         version: dict[str, Any]) -> Owner: ...
    def get_aggregate_row(self, owner: Any) -> dict[str, Any] | None: ...
    def get_aggregate(self, owner: Any) -> dict[str, Any] | None: ...
    def list_aggregates(self, owner_type: str) -> list[dict[str, Any]]: ...
    def update_aggregate(self, owner: Any, values: dict[str, Any]) -> None: ...
    def running_assessment_ids(self, request_id: int) -> list[int]: ...
    def set_facts(self, aggregate: dict[str, Any], facts: dict[str, Any], actor: str,
                  source_type: str, source_reference: str | None) -> None: ...

    # --- nodes ---------------------------------------------------------------
    def create_step_instances(self, owner: Any, version_id: int) -> None: ...
    def remap_step_instances(self, owner: Any, target_version_id: int) -> dict[str, int]: ...
    def get_step(self, step_id: int) -> dict[str, Any] | None: ...
    def list_steps_by_execution(self, owner: Any, status: str) -> list[dict[str, Any]]: ...
    def incoming(self, owner: Any, step_definition_id: int) -> list[dict[str, Any]]: ...
    def update_step(self, step_id: int, values: dict[str, Any]) -> None: ...
    def cancel_open_work(self, owner: Any) -> None: ...
    def record_attempt_start(self, step_id: int, iteration: int) -> None: ...
    def record_attempt_end(self, step_id: int, iteration: int, outcome: str, result: dict[str, Any]) -> None: ...

    # --- work ----------------------------------------------------------------
    def list_work(self, **filters: Any) -> dict[str, Any]: ...
    def create_candidates(self, step_id: int, candidates: list[dict[str, Any]]) -> None: ...
    def candidate_allowed(self, step_id: int, actor: dict[str, Any]) -> bool: ...
    def create_assignment(self, step_id: int, assignee_type: str, assignee: str,
                          organization_id: str | None = None, assigned_by: str | None = None,
                          reason: str | None = None, due_at: str | None = None) -> None: ...
    def replace_assignments(self, step_id: int, assignee_type: str, assignee: str,
                            organization_id: str | None = None, assigned_by: str | None = None,
                            reason: str | None = None) -> None: ...

    # --- signals, jobs and timers -------------------------------------------
    def insert_signal(self, command: dict[str, Any], owner: Any) -> None: ...
    def unconsumed_signal(self, owner: Any, signal_type: str,
                          correlation_key: str | None) -> dict[str, Any] | None: ...
    def consume_signal(self, signal_id: int, step_id: int) -> None: ...
    def create_automation_job(self, owner: Any, step: dict[str, Any]) -> None: ...
    def claim_jobs(self, worker_id: str, limit: int = 10, lease_seconds: int = 60) -> list[dict[str, Any]]: ...
    def get_job(self, job_id: int) -> dict[str, Any] | None: ...
    def update_job(self, job_id: int, values: dict[str, Any]) -> None: ...
    def job_for_step(self, step_id: int) -> dict[str, Any] | None: ...
    def requeue_job_for_step(self, step_id: int) -> bool: ...
    def create_timer(self, owner: Any, step: dict[str, Any], due_at: str,
                     action: str = "COMPLETE_STEP") -> None: ...
    def due_timers(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def fire_timer(self, timer_id: int) -> None: ...

    # --- the one log, the one outbox, the one inbox --------------------------
    def append_event(self, owner: Any, event_type: str, actor: str,
                     step_id: int | None = None, previous: str | None = None,
                     new: str | None = None, payload: dict[str, Any] | None = None,
                     actor_org_id: str | None = None) -> None: ...
    def append_domain_event(self, aggregate_type: str, aggregate_id: str, event_type: str,
                            actor: str, **fields: Any) -> dict[str, Any]: ...
    def list_events(self, aggregate_type: str, aggregate_id: str,
                    limit: int = 200, offset: int = 0) -> list[dict[str, Any]]: ...
    def record_inbox(self, event: dict[str, Any]) -> dict[str, Any]: ...
    def inbox_event(self, connector_name: str, provider_event_id: str) -> dict[str, Any] | None: ...
    def insert_inbox_event(self, data: dict[str, Any]) -> int: ...
    def claim_inbox_events(self, worker_id: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def mark_inbox_processed(self, inbox_id: int, error: str | None = None) -> None: ...
    def dead_letter_events(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def redrive_outbox(self, outbox_id: int) -> bool: ...
    def delivered_subscription_ids(self, outbox_id: int) -> set[int]: ...

    # --- idempotency and operations -----------------------------------------
    def command_result(self, command_id: str) -> dict[str, Any] | None: ...
    def record_command(self, command_id: str, owner: Any, action: str,
                       revision: int | None = None) -> None: ...
    def stuck_aggregates(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def operational_counters(self) -> dict[str, int]: ...
