from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol


class WorkflowRepository(Protocol):
    """Persistence boundary implemented by database-specific adapters."""

    def transaction(self) -> AbstractContextManager[None]: ...
    def import_template(self, template: dict[str, Any]) -> dict[str, int]: ...
    def list_templates(self) -> list[dict[str, Any]]: ...
    def get_template(self, version_id: int) -> dict[str, Any] | None: ...
    def get_published_version(self, version_id: int) -> dict[str, Any] | None: ...
    def fsm_initial_state(self, fsm_version_id: int) -> str: ...
    def find_fsm_transition(self, fsm_version_id: int, state: str, action: str) -> dict[str, Any] | None: ...
    def state_is_terminal(self, fsm_version_id: int, state: str) -> bool: ...
    def command_result(self, command_id: str) -> dict[str, Any] | None: ...
    def record_command(self, command_id: str, workflow_id: int, action: str,
                       revision: int | None = None) -> None: ...
    def list_work(self, **filters: Any) -> dict[str, Any]: ...
    def fsm_has_state(self, fsm_version_id: int, state: str) -> bool: ...
    def remap_step_instances(self, workflow_id: int,
                             target_version_id: int) -> dict[str, int]: ...
    def stuck_workflows(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def dead_letter_events(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def redrive_outbox(self, outbox_id: int) -> bool: ...
    def operational_counters(self) -> dict[str, int]: ...
    def requeue_job_for_step(self, step_id: int) -> bool: ...
    def create_workflow(self, data: dict[str, Any], version: dict[str, Any]) -> int: ...
    def add_subjects(self, workflow_id: int, subjects: list[dict[str, Any]]) -> None: ...
    def create_step_instances(self, workflow_id: int, version_id: int) -> None: ...
    def get_instance_row(self, workflow_id: int) -> dict[str, Any] | None: ...
    def list_workflows(self) -> list[dict[str, Any]]: ...
    def get_workflow(self, workflow_id: int) -> dict[str, Any] | None: ...
    def get_step(self, step_id: int) -> dict[str, Any] | None: ...
    def list_steps_by_execution(self, workflow_id: int, status: str) -> list[dict[str, Any]]: ...
    def incoming(self, workflow_id: int, step_definition_id: int) -> list[dict[str, Any]]: ...
    def update_step(self, step_id: int, values: dict[str, Any]) -> None: ...
    def update_workflow(self, workflow_id: int, values: dict[str, Any]) -> None: ...
    def set_facts(self, workflow: dict[str, Any], facts: dict[str, Any], actor: str,
                  source_type: str, source_reference: str | None) -> None: ...
    def create_candidates(self, step_id: int, candidates: list[dict[str, Any]]) -> None: ...
    def candidate_allowed(self, step_id: int, actor: dict[str, Any]) -> bool: ...
    def create_assignment(self, step_id: int, assignee_type: str, assignee: str,
                          organization_id: str | None = None, assigned_by: str | None = None,
                          reason: str | None = None, due_at: str | None = None) -> None: ...
    def replace_assignments(self, step_id: int, assignee_type: str, assignee: str,
                            organization_id: str | None = None, assigned_by: str | None = None,
                            reason: str | None = None) -> None: ...
    def record_attempt_start(self, step_id: int, iteration: int) -> None: ...
    def record_attempt_end(self, step_id: int, iteration: int, outcome: str, result: dict[str, Any]) -> None: ...
    def insert_signal(self, command: dict[str, Any], workflow_id: int) -> None: ...
    def inbox_event(self, connector_name: str, provider_event_id: str) -> dict[str, Any] | None: ...
    def insert_inbox_event(self, data: dict[str, Any]) -> int: ...
    def mark_inbox_processed(self, inbox_id: int, error: str | None = None) -> None: ...
    def unconsumed_signal(self, workflow_id: int, signal_type: str,
                          correlation_key: str | None) -> dict[str, Any] | None: ...
    def consume_signal(self, signal_id: int, step_id: int) -> None: ...
    def create_automation_job(self, workflow_id: int, step: dict[str, Any]) -> None: ...
    def claim_jobs(self, worker_id: str, limit: int = 10, lease_seconds: int = 60) -> list[dict[str, Any]]: ...
    def get_job(self, job_id: int) -> dict[str, Any] | None: ...
    def update_job(self, job_id: int, values: dict[str, Any]) -> None: ...
    def create_timer(self, workflow_id: int, step: dict[str, Any], due_at: str,
                     action: str = "COMPLETE_STEP") -> None: ...
    def due_timers(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def fire_timer(self, timer_id: int) -> None: ...
    def job_for_step(self, step_id: int) -> dict[str, Any] | None: ...
    def cancel_open_work(self, workflow_id: int) -> None: ...
    def running_child_ids(self, workflow_id: int) -> list[int]: ...
    def delivered_subscription_ids(self, outbox_id: int) -> set[int]: ...
    def append_event(self, workflow_id: int, event_type: str, actor: str,
                     step_id: int | None = None, previous: str | None = None,
                     new: str | None = None, payload: dict[str, Any] | None = None,
                     actor_org_id: str | None = None) -> None: ...
