from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol


class WorkflowRepository(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def import_template(self, template: dict[str, Any]) -> dict[str, int]: ...
    def list_templates(self) -> list[dict[str, Any]]: ...
    def get_template(self, version_id: int) -> dict[str, Any] | None: ...
    def get_published_version(self, version_id: int) -> dict[str, Any] | None: ...
    def command_result(self, command_id: str) -> dict[str, Any] | None: ...
    def record_command(self, command_id: str, workflow_id: int, action: str, result: dict[str, Any]) -> None: ...
    def create_workflow(self, data: dict[str, Any]) -> int: ...
    def add_subjects(self, workflow_id: int, subjects: list[dict[str, Any]]) -> None: ...
    def create_step_instances(self, workflow_id: int, version_id: int) -> None: ...
    def get_instance_row(self, workflow_id: int) -> dict[str, Any] | None: ...
    def list_workflows(self) -> list[dict[str, Any]]: ...
    def get_workflow(self, workflow_id: int) -> dict[str, Any] | None: ...
    def list_not_ready_steps(self, workflow_id: int) -> list[dict[str, Any]]: ...
    def list_ready_steps(self, workflow_id: int) -> list[dict[str, Any]]: ...
    def incoming(self, workflow_id: int, step_definition_id: int) -> list[dict[str, Any]]: ...
    def update_step(self, step_id: int, values: dict[str, Any]) -> None: ...
    def update_workflow(self, workflow_id: int, values: dict[str, Any]) -> None: ...
    def get_step(self, step_id: int) -> dict[str, Any] | None: ...
    def create_assignment(self, step_id: int, assignee_type: str, assignee: str) -> None: ...
    def replace_assignments(self, step_id: int, assignee_type: str, assignee: str) -> None: ...
    def append_event(self, workflow_id: int, event_type: str, actor: str, step_id: int | None = None, previous: str | None = None, new: str | None = None, payload: dict[str, Any] | None = None) -> None: ...

