import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'/api';
async function api(path, options={}) { const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...options}); if(!r.ok) throw new Error((await r.json()).detail||r.statusText); return r.json(); }
const badge=s=><span className={'badge '+String(s).toLowerCase().replaceAll('_','-')}>{String(s).replaceAll('_',' ')}</span>;

function App(){
  const [page,setPage]=useState('instances'); const [templates,setTemplates]=useState([]); const [instances,setInstances]=useState([]); const [selected,setSelected]=useState(null); const [error,setError]=useState('');
  const refresh=async()=>{try{setError(''); const [t,w]=await Promise.all([api('/templates'),api('/workflows')]);setTemplates(t);setInstances(w)}catch(e){setError(e.message)}};
  useEffect(()=>{refresh()},[]);
  const open=async id=>{try{setSelected(await api('/workflows/'+id));setPage('detail')}catch(e){setError(e.message)}};
  return <><header><div><strong>ReviewFlow</strong><small>Configurable review workflow engine</small></div><nav><button className={page==='instances'?'active':''} onClick={()=>setPage('instances')}>Workflow runs</button><button className={page==='launch'?'active':''} onClick={()=>setPage('launch')}>Launch</button><button className={page==='templates'?'active':''} onClick={()=>setPage('templates')}>Templates</button><button className={page==='import'?'active':''} onClick={()=>setPage('import')}>Import template</button></nav></header><main>{error&&<div className="error">{error}</div>}{page==='instances'&&<Instances items={instances} open={open}/>} {page==='launch'&&<Launch templates={templates} onCreated={async w=>{await refresh();setSelected(w);setPage('detail')}}/>}{page==='templates'&&<Templates items={templates}/>} {page==='import'&&<ImportTemplate onDone={async()=>{await refresh();setPage('templates')}}/>}{page==='detail'&&selected&&<Detail item={selected} setItem={setSelected}/>}</main></>
}

function Instances({items,open}){return <section><div className="title"><div><p className="eyebrow">RUNTIME</p><h1>Workflow runs</h1><p>Each run uses an immutable workflow version and keeps its own step and event history.</p></div></div><div className="panel table"><table><thead><tr><th>ID</th><th>Title</th><th>Template</th><th>Stage</th><th>Status</th><th></th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>WF-{x.id}</td><td><strong>{x.title}</strong></td><td>{x.workflow_name}</td><td>{x.current_stage||'—'}</td><td>{badge(x.status)}</td><td><button onClick={()=>open(x.id)}>Open</button></td></tr>):<tr><td colSpan="6" className="empty">No workflow runs yet. Launch a seeded template to begin.</td></tr>}</tbody></table></div></section>}

function Launch({templates,onCreated}){const [template,setTemplate]=useState(templates[0]?.workflow_version_id||'');const [title,setTitle]=useState('Zscaler connector security review');const [app,setApp]=useState('APP-100');const [tech,setTech]=useState('TECH-200');const [identity,setIdentity]=useState(true);const [network,setNetwork]=useState(true);const [busy,setBusy]=useState(false);useEffect(()=>{if(!template&&templates[0])setTemplate(templates[0].workflow_version_id)},[templates]);async function submit(e){e.preventDefault();setBusy(true);try{const subjects=[];if(app)subjects.push({subject_type:'APPLICATION',subject_id:app,source_system:'Application Registry'});if(tech)subjects.push({subject_type:'TECHNOLOGY',subject_id:tech,source_system:'Technology Catalogue',relationship:'IN_SCOPE'});const w=await api('/workflows',{method:'POST',body:JSON.stringify({workflow_version_id:Number(template),title,created_by:'demo.user',input:{identity_review:identity,network_review:network},subjects})});onCreated(w)}finally{setBusy(false)}}return <section><p className="eyebrow">START</p><h1>Launch a workflow</h1><p>The selected template determines the graph. Input data controls conditional branches.</p><form className="panel form" onSubmit={submit}><label>Workflow template<select value={template} onChange={e=>setTemplate(e.target.value)}>{templates.filter(t=>t.version_status==='PUBLISHED').map(t=><option key={t.workflow_version_id} value={t.workflow_version_id}>{t.name} · v{t.version_number}</option>)}</select></label><label>Run title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><div className="cols"><label>Application ID (optional)<input value={app} onChange={e=>setApp(e.target.value)}/></label><label>Technology ID (optional)<input value={tech} onChange={e=>setTech(e.target.value)}/></label></div><fieldset><legend>Information Security Review branch inputs</legend><label className="check"><input type="checkbox" checked={identity} onChange={e=>setIdentity(e.target.checked)}/> Activate Identity SME review</label><label className="check"><input type="checkbox" checked={network} onChange={e=>setNetwork(e.target.checked)}/> Activate Network SME review</label></fieldset><button className="primary" disabled={busy}>{busy?'Launching…':'Launch workflow'}</button></form></section>}

function Templates({items}){return <section><p className="eyebrow">CONFIGURATION</p><h1>Workflow templates</h1><p>Published versions are immutable inputs to new workflow runs.</p><div className="cards">{items.map(t=><article className="panel" key={t.workflow_version_id}><div className="row"><span className="kicker">{t.domain}</span>{badge(t.version_status)}</div><h2>{t.name}</h2><p>{t.description}</p><div className="meta"><span>Version {t.version_number}</span><span>{t.step_count} steps</span><span>{t.key}</span></div></article>)}</div></section>}

const starter=JSON.stringify({key:'architecture-review',name:'Security Architecture Review',description:'Example imported workflow.',domain:'SECURITY_ARCHITECTURE',version:1,publish:true,steps:[{key:'submit',name:'Submit architecture',type:'HUMAN_TASK',stage:'Submission',assignment_role:'REQUESTOR'},{key:'review',name:'Architecture review',type:'HUMAN_TASK',stage:'Review',assignment_role:'SECURITY_ARCHITECT'},{key:'end',name:'Complete review',type:'END',stage:'End'}],transitions:[{from_step:'submit',to_step:'review'},{from_step:'review',to_step:'end'}]},null,2);
function ImportTemplate({onDone}){const [value,setValue]=useState(starter);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function submit(){setBusy(true);setMessage('');try{await api('/templates/import',{method:'POST',body:value});setMessage('Template imported.');onDone()}catch(e){setMessage(e.message)}finally{setBusy(false)}}return <section><p className="eyebrow">CONFIGURATION</p><h1>Import a template</h1><p>Edit the JSON to define steps, transitions, conditions, roles, and join rules.</p><div className="panel form"><label>Template JSON<textarea className="editor" value={value} onChange={e=>setValue(e.target.value)} spellCheck="false"/></label><div className="row"><span className="hint">Create a new version number when updating an existing template key.</span><button className="primary" onClick={submit} disabled={busy}>{busy?'Importing…':'Validate and import'}</button></div>{message&&<p>{message}</p>}</div></section>}

const actionsFor={READY:['start','skip'],ASSIGNED:['start','skip'],IN_PROGRESS:['request_clarification','wait','complete','fail'],WAITING:['resume'],CLARIFICATION_REQUIRED:['respond'],RESPONSE_RECEIVED:['resume','complete']};
function Detail({item,setItem}){const [busy,setBusy]=useState(null);const [payload,setPayload]=useState('{}');async function act(step,action){setBusy(step.id+action);try{const updated=await api('/steps/'+step.id+'/actions',{method:'POST',body:JSON.stringify({action,actor:'demo.user',payload:JSON.parse(payload||'{}')})});setItem(updated)}catch(e){alert(e.message)}finally{setBusy(null)}}const active=item.steps.filter(s=>!['NOT_READY','COMPLETED','SKIPPED','CANCELLED'].includes(s.state));return <section><div className="row"><div><p className="eyebrow">WF-{item.id} · {item.workflow_name} v{item.version_number}</p><h1>{item.title}</h1></div>{badge(item.status)}</div><div className="summary"><div><span>Current stage</span><strong>{item.current_stage||'—'}</strong></div><div><span>Active work</span><strong>{active.length}</strong></div><div><span>Subjects</span><strong>{item.subjects.length}</strong></div><div><span>Events</span><strong>{item.events.length}</strong></div></div><div className="tabs"><h2>Steps</h2><label>Action result JSON<input value={payload} onChange={e=>setPayload(e.target.value)}/></label></div><div className="steps">{item.steps.map(step=><article className={'panel step '+(step.state==='NOT_READY'?'muted':'')} key={step.id}><div className="stepnum">{step.id}</div><div className="stepbody"><div className="row"><div><span className="kicker">{step.stage} · {step.step_type}</span><h3>{step.name}</h3></div>{badge(step.state)}</div>{step.description&&<p>{step.description}</p>}<div className="meta">{step.assignments.map(a=><span key={a.id}>{a.assignee_type}: {a.assignee}</span>)}</div>{actionsFor[step.state]&&<div className="actions">{actionsFor[step.state].map(a=><button className={a==='complete'?'primary':''} disabled={busy} key={a} onClick={()=>act(step,a)}>{a.replaceAll('_',' ')}</button>)}</div>}</div></article>)}</div><h2>Subjects</h2><div className="panel chips">{item.subjects.map(s=><span key={s.id}>{s.subject_type}: {s.subject_id} <small>{s.source_system}</small></span>)}</div><h2>Audit history</h2><div className="panel timeline">{item.events.map(e=><div key={e.id}><time>{new Date(e.created_at+'Z').toLocaleString()}</time><strong>{e.event_type.replaceAll('_',' ')}</strong><span>{e.actor}{e.previous_state?` · ${e.previous_state} → ${e.new_state}`:''}</span></div>)}</div></section>}

createRoot(document.getElementById('root')).render(<App/>);
